export const sports = [
  "Alpine Skiing",
  "American Football",
  "Archery",
  "Artistic Gymnastics",
  "Artistic Swimming",
  "Athletics",
  "Badminton",
  "Bandy",
  "Baseball",
  "Basketball",
  "Beach Soccer",
  "Beach Volleyball",
  "Biathlon",
  "Bobsleigh",
  "Boxing",
  "Canoeing",
  "Chess",
  "Cricket",
  "Cross-Country Skiing",
  "Curling",
  "Cycling",
  "Diving",
  "Equestrian",
  "Fencing",
  "Field Hockey",
  "Figure Skating",
  "Football",
  "Freestyle Skiing",
  "Futsal",
  "Golf",
  "Handball",
  "Ice Hockey",
  "Judo",
  "Karate",
  "Lacrosse",
  "Luge",
  "Modern Pentathlon",
  "Motor Sports",
  "Motorbike Racing",
  "Multi-Sport Events",
  "Nordic Combined",
  "Open Water Swimming",
  "Rhythmic Gymnastics",
  "Rowing",
  "Rugby",
  "Sailing",
  "Sambo",
  "Shooting",
  "Short Track",
  "Skateboarding",
  "Skeleton",
  "Ski Jumping",
  "Snooker",
  "Snowboarding",
  "Softball",
  "Speed Skating",
  "Speedboat Racing",
  "Sport Climbing",
  "Surfing",
  "Swimming",
  "Table Tennis",
  "Taekwondo",
  "Tennis",
  "Trampoline",
  "Triathlon",
  "Volleyball",
  "Water Polo",
  "Weightlifting",
  "Wrestling",
];